version: "3.9"

services:
  web:
    image: php:8.2-apache
    container_name: PHP
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - "./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    depends_on:
      - db
    command: bash -c "a2enmod rewrite && docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:8
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smsdv3
      MYSQL_USER: user
      MYSQL_PASSWORD: username
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db

  api:
    image: python:3.13
    container_name: API
    ports:
     - "8001:8000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "pip install fastapi uvicorn mysql-connector-python && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=smsdv3
      - DB_PREFIX=

volumes:
  db_data:
